name: Dynamic Youtube Links

on:
    schedule:
        - cron: "0 5 * * *"
    workflow_dispatch:

permissions:
    contents: write


jobs:
    links:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                comment_tag_name: "YOUTUBE"
                feed_list: https://www.youtube.com/feeds/videos.xml?channel_id=UCqoZcZ5SDuxexeKhCvmqcqg
